fragment PageParts on Page {
  __typename
  title
  hero {
    __typename
    title
    italicTitle
    description
    buttonPrimary
    buttonSecondary
    image
  }
  welcome {
    __typename
    text
  }
  bandeau {
    __typename
    image
    title
    subtitle
  }
  location {
    __typename
    image
    title
    text
  }
  sections {
    __typename
    ... on PageSectionsWorkshopBlock {
      title
      subtitle
      priceTag
      priceSub
      description
      features
      image
      buttonText
      buttonLink
    }
    ... on PageSectionsGridSection {
      title
      items {
        __typename
        title
        text
        label
        image
      }
    }
    ... on PageSectionsRichTextSection {
      body
    }
    ... on PageSectionsPolaroidBlock {
      image
      caption
    }
    ... on PageSectionsGallerySection {
      title
      images {
        __typename
        src
        alt
      }
    }
  }
}
